//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int A_Id { get; set; }
        public int U_Id { get; set; }
        public int J_Id { get; set; }
        public int C_Id { get; set; }
        public string resume { get; set; }
        public string applyDate { get; set; }
        public string Status { get; set; }
    }
}
