//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JobSearch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyMVCProjectDBEntities : DbContext
    {
        public MyMVCProjectDBEntities()
            : base("name=MyMVCProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyReg> CompanyRegs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<UserReg> UserRegs { get; set; }
        public virtual DbSet<Apply> Applies { get; set; }
    
        public virtual ObjectResult<Nullable<int>> MaxIdLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxIdLogin");
        }
    
        public virtual int sp_companyReg(Nullable<int> cid, string cna, string caddr, string cphone, string cemail, string cwebsite, string clocation)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var caddrParameter = caddr != null ?
                new ObjectParameter("caddr", caddr) :
                new ObjectParameter("caddr", typeof(string));
    
            var cphoneParameter = cphone != null ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            var cwebsiteParameter = cwebsite != null ?
                new ObjectParameter("cwebsite", cwebsite) :
                new ObjectParameter("cwebsite", typeof(string));
    
            var clocationParameter = clocation != null ?
                new ObjectParameter("clocation", clocation) :
                new ObjectParameter("clocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_companyReg", cidParameter, cnaParameter, caddrParameter, cphoneParameter, cemailParameter, cwebsiteParameter, clocationParameter);
        }
    
        public virtual int sp_login(string una, string pwd, ObjectParameter status)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_login", unaParameter, pwdParameter, status);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginId(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginId", unaParameter, pwdParameter);
        }
    
        public virtual int sp_userReg(Nullable<int> uid, string una, Nullable<int> uage, string uaddr, string uphone, string uemail, string uqual, string uexp, string uskill, string uphoto, string uresume)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var uageParameter = uage.HasValue ?
                new ObjectParameter("uage", uage) :
                new ObjectParameter("uage", typeof(int));
    
            var uaddrParameter = uaddr != null ?
                new ObjectParameter("uaddr", uaddr) :
                new ObjectParameter("uaddr", typeof(string));
    
            var uphoneParameter = uphone != null ?
                new ObjectParameter("uphone", uphone) :
                new ObjectParameter("uphone", typeof(string));
    
            var uemailParameter = uemail != null ?
                new ObjectParameter("uemail", uemail) :
                new ObjectParameter("uemail", typeof(string));
    
            var uqualParameter = uqual != null ?
                new ObjectParameter("uqual", uqual) :
                new ObjectParameter("uqual", typeof(string));
    
            var uexpParameter = uexp != null ?
                new ObjectParameter("uexp", uexp) :
                new ObjectParameter("uexp", typeof(string));
    
            var uskillParameter = uskill != null ?
                new ObjectParameter("uskill", uskill) :
                new ObjectParameter("uskill", typeof(string));
    
            var uphotoParameter = uphoto != null ?
                new ObjectParameter("uphoto", uphoto) :
                new ObjectParameter("uphoto", typeof(string));
    
            var uresumeParameter = uresume != null ?
                new ObjectParameter("uresume", uresume) :
                new ObjectParameter("uresume", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userReg", uidParameter, unaParameter, uageParameter, uaddrParameter, uphoneParameter, uemailParameter, uqualParameter, uexpParameter, uskillParameter, uphotoParameter, uresumeParameter);
        }
    
        public virtual int sp_loginsert(Nullable<int> rid, string una, string pw, string utype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loginsert", ridParameter, unaParameter, pwParameter, utypeParameter);
        }
    
        public virtual ObjectResult<string> sp_loginType(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_loginType", unaParameter, pwdParameter);
        }
    
        public virtual int sp_jobinsert(Nullable<int> cid, string tit, string exp, string skill, Nullable<int> vac, string dte, string status)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var titParameter = tit != null ?
                new ObjectParameter("tit", tit) :
                new ObjectParameter("tit", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var skillParameter = skill != null ?
                new ObjectParameter("skill", skill) :
                new ObjectParameter("skill", typeof(string));
    
            var vacParameter = vac.HasValue ?
                new ObjectParameter("vac", vac) :
                new ObjectParameter("vac", typeof(int));
    
            var dteParameter = dte != null ?
                new ObjectParameter("dte", dte) :
                new ObjectParameter("dte", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobinsert", cidParameter, titParameter, expParameter, skillParameter, vacParameter, dteParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_SelectAllUsers_Result> sp_SelectAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectAllUsers_Result>("sp_SelectAllUsers");
        }
    
        public virtual int sp_jobsearches(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearches", qryParameter);
        }
    
        public virtual int sp_applicationInsert(Nullable<int> uid, Nullable<int> jid, Nullable<int> cid, string resume, string dte, string status)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var resumeParameter = resume != null ?
                new ObjectParameter("resume", resume) :
                new ObjectParameter("resume", typeof(string));
    
            var dteParameter = dte != null ?
                new ObjectParameter("dte", dte) :
                new ObjectParameter("dte", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_applicationInsert", uidParameter, jidParameter, cidParameter, resumeParameter, dteParameter, statusParameter);
        }
    }
}
