//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg
    {
        public int U_Id { get; set; }
        public string UName { get; set; }
        public int UAge { get; set; }
        public string UAddress { get; set; }
        public string UPhone { get; set; }
        public string UEmail { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string Skills { get; set; }
        public string Photo { get; set; }
        public string Resume { get; set; }
    }
}
